Updates cli flag handling
This commit is a fix for the following error:

```
serve.go:140:15: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type
cli.Flag in array or slice literal:
        cli.BoolFlag does not implement cli.Flag (Apply method has pointer
        receiver)
```

It switches from using codegangsta/cli to urfave/cli, since the former seems to
no longer be maintained

This commit also adds a go module file to lock down dependencies.

This fixes #4.